name: helm
"on":
  push:
    tags:
      - helm-*
jobs:
  helm:
    name: Build and push Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
      - name: Build and push Helm chart
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | helm registry login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          tag=$(echo ${{ github.ref_name }} | sed 's/helm-//')
          helm package --version "$tag" helm
          helm push "helm-dogoncall-$tag.tgz" oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}
