name: Release
"on":
  push:
    tags:
      - "*"
jobs:
  docker:
    name: Build and push Docker image
    if: ${{ ! contains(github.ref_name, 'dev') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
  helm:
    name: Build and push Helm chart
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
      - name: Build and push Helm chart
        run: |
          helm version
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | helm registry login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          helm package --version ${{ github.ref_name }} --app-version ${{ github.ref_name }} helm
          helm push helm-dogoncall-${{ github.ref_name }}.tgz oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}
